# Add your secrets here
# This file is for reference only - Streamlit Cloud won't read this file
# You need to add these secrets via the Streamlit Cloud UI

# Your Google API key for Gemini
GOOGLE_API_KEY = "your_api_key_here" 